services:
  mysql-container:
    image: mysql:latest
  
  postgres-container:
    image: postgres:latest
  
  products-services:
    image: ${DOCKER_REGISTRY-}products-microservice
    build:
      context: .
      dockerfile: eCommerce.ProductsService/eCommerce.Products.API/Dockerfile
  
  users-services:
    image: ${DOCKER_REGISTRY-}users-microservice
    build:
      context: .
      dockerfile: eCommerce.UsersService/eCommerce.Users.API/Dockerfile

volumes:
  mysql_data:
  postgres_data:
