services:
  products-db:
    container_name: products-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=eCommerceProducts
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - products_data:/var/lib/postgresql/data/

  users-db:
    container_name: users-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=eCommerceUsers
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - users_data:/var/lib/postgresql/data/

  order-db:
    container_name: order-db
    ports:
      - "27017:27017"
    volumes:
      - ../order-db:/docker-entrypoint-initdb.d

  products-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      #      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=root007
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__Database=Server=products-db;Database=eCommerceProducts;Username=postgres;Password=postgres;Include Error Detail=true
    depends_on:
      - products-db
    ports:
      - "6000:8080"
    #      - "6061:8081"
    volumes:
      - ~/.aspnet/https:/https:ro

  users-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=9000
      #      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=root007
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__Database=Server=users-db;Database=eCommerceUsers;Username=postgres;Password=postgres;Include Error Detail=true
    depends_on:
      - users-db
    ports:
      - "7000:9000"
    #      - "7071:8081"
    volumes:
      - ~/.aspnet/https:/https:ro

  order-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      #      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=root007
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - MONGODB_HOST=order-db
      - UsersMicroserviceName=users-service
      - UsersMicroservicePort=9000
      - ProductsMicroserviceName=products-service
      - ProductsMicroservicePort=8080
      - ConnectionStrings__Redis=redis:6379
    depends_on:
      - order-db
    ports:
      - "9001:8080"
    #      - "9091:8081"
    volumes:
      - ~/.aspnet/https:/https:ro
  
  redis:
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ../redis-cache:/data
  
  gateway.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    #      - ASPNETCORE_HTTPS_PORTS=8081
    #      - ASPNETCORE_Kestrel__Certificates__Default__Password=root007
    #      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    depends_on:
      - products-service
      - users-service
      - order-service
    ports:
      - "4000:8080"
