services:
  products-db:
    container_name: products-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=eCommerceProducts
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - products_data:/var/lib/postgresql/data/
  
  users-db:
    container_name: users-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=eCommerceUsers
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - users_data:/var/lib/postgresql/data/
  
  products-services:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=root007
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__Database=Server=products-db;Database=eCommerceProducts;Username=postgres;Password=postgres;Include Error Detail=true
    depends_on:
      - products-db
    ports:
      - "6000:8080"
      - "6061:8081"
    volumes:
      - ~/.aspnet/https:/https:ro
  
  users-services:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=root007
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__Database=Server=users-db;Database=eCommerceUsers;Username=postgres;Password=postgres;Include Error Detail=true
    depends_on:
      - users-db
    ports:
      - "7000:8080"
      - "7071:8081"
    volumes:
      - ~/.aspnet/https:/https:ro