services:
  products-db:
    image: postgres:latest
  
  users-db:
    image: postgres:latest
  
  products-services:
    image: ${DOCKER_REGISTRY-}products-microservice
    build:
      context: .
      dockerfile: eCommerce.ProductsService/eCommerce.Products.API/Dockerfile
  
  users-services:
    image: ${DOCKER_REGISTRY-}users-microservice
    build:
      context: .
      dockerfile: eCommerce.UsersService/eCommerce.Users.API/Dockerfile

volumes:
  products_data:
  users_data:
