services:
  products-db:
    container_name: products-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=eCommerceProducts
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - products_data:/var/lib/postgresql/data/
  
  users-db:
    container_name: users-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=eCommerceUsers
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - users_data:/var/lib/postgresql/data/
  
  order-db:
    container_name: order-db
    ports:
      - "27017:27017"
    volumes:
      - ../order-db:/docker-entrypoint-initdb.d
    networks:
      - orders-mongo-network
  
  products-services:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=root007
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__Database=Server=products-db;Database=eCommerceProducts;Username=postgres;Password=postgres;Include Error Detail=true
    depends_on:
      - products-db
    ports:
      - "6000:6000"
      - "6061:6061"
    volumes:
      - ~/.aspnet/https:/https:ro
  
  users-services:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=root007
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__Database=Server=users-db;Database=eCommerceUsers;Username=postgres;Password=postgres;Include Error Detail=true
    depends_on:
      - users-db
    ports:
      - "7000:7000"
      - "7071:7071"
    volumes:
      - ~/.aspnet/https:/https:ro
  
  order-services:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=root007
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - MONGODB_HOST=order-db
      - UsersMicroserviceName=localhost
      - UsersMicroservicePort=7071
      - ProductsMicroserviceName=localhost
      - ProductsMicroservicePort=6061
    depends_on:
      - order-db
    ports:
      - "9000:9000"
      - "9091:9091"
    volumes:
      - ~/.aspnet/https:/https:ro
    networks:
      - orders-mongo-network

networks:
  orders-mongo-network:
    driver: bridge