services:
  products-db:
    image: postgres:latest
  
  users-db:
    image: postgres:latest
  
  order-db:
    image: mongo:latest
  
  products-service:
    image: ${DOCKER_REGISTRY-}products-service
    build:
      context: .
      dockerfile: eCommerce.ProductsService/eCommerce.Products.API/Dockerfile
  
  users-service:
    image: ${DOCKER_REGISTRY-}users-service
    build:
      context: .
      dockerfile: eCommerce.UsersService/eCommerce.Users.API/Dockerfile
  
  order-service:
    image: ${DOCKER_REGISTRY-}order-service
    build:
      context: .
      dockerfile: eCommerce.OrdersService/eCommerce.Orders.API/Dockerfile

volumes:
  products_data:
  users_data:
